'-----------------------------------------------------------------------------------  
' for the CX16
'
' COLOR CODES CONSTs 
'
' sadLogic / Steve De George SR.   Nov 2025, Kherson Ukraine
' Compile with nxtBasic: https://github.com/unartic/nxtBasic   Windows - CRLF
'-----------------------------------------------------------------------------------

CONST COLOR_BLACK = 0
CONST COLOR_WHITE = 1
CONST COLOR_RED = 2
CONST COLOR_CYAN = 3
CONST COLOR_PURPLE  = 4
CONST COLOR_GREEN = 5
CONST COLOR_BLUE = 6
CONST COLOR_YELLOW = 7
CONST COLOR_ORANGE = 8
CONST COLOR_BROWN = 9
CONST COLOR_LIGHT_RED = 10
CONST COLOR_DARK_GRAY = 11
CONST COLOR_GRAY = 12
CONST COLOR_LIGHT_GREEN = 13
CONST COLOR_LIGHT_BLUE = 14
CONST COLOR_LIGHT_GRAY = 15