'-----------------------------------------------------------------------------------  
' for the CX16
'
' CONTROL CODES CONSTs 
'
' sadLogic / Steve De George SR.   Nov 2025, Kherson Ukraine
' Compile with nxtBasic: https://github.com/unartic/nxtBasic   Windows - CRLF
'-----------------------------------------------------------------------------------

CONST REV_ON = CHR$($12)
CONST QUOTES_CHAR = CHR$(34)
CONST BELL = CHR$($07)

